artifact_location: file:///home/mle-user/mle_projects/mle-project-sprint-2-v001/mlflow_experiments_store/0
creation_time: 1714983814393
experiment_id: '0'
last_update_time: 1714983814393
lifecycle_stage: active
name: Default
